# Generated by Django 2.2.1 on 2019-06-17 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrese', models.TextField()),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
                ('ph_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gardian_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=15)),
                ('f_name', models.CharField(max_length=15)),
                ('m_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('occupation', models.CharField(default='', max_length=20, null=True)),
                ('annual_income', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_num', models.IntegerField()),
                ('strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_info',
            fields=[
                ('T_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=15)),
                ('m_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('birthdate', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=10)),
                ('img', models.FileField(blank=True, upload_to='')),
                ('is_class_tec', models.BooleanField(default=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databasetset.Contact_info')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databasetset.Standard_info')),
                ('teacher', models.ManyToManyField(to='databasetset.Teacher_info')),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('S_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, max_length=15)),
                ('m_name', models.CharField(blank=True, max_length=15)),
                ('l_name', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('birthdate', models.DateField(null=True)),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('password', models.CharField(blank=True, max_length=10)),
                ('img', models.FileField(blank=True, upload_to='')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databasetset.Teacher_info')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databasetset.Contact_info')),
                ('gardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databasetset.Gardian_info')),
                ('std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databasetset.Standard_info')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='standard_info',
            name='class_teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databasetset.Teacher_info'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to='nots')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasetset.Teacher_info')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('end_date', models.DateField()),
                ('msg', models.CharField(max_length=150)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasetset.Teacher_info')),
            ],
        ),
    ]
